<option value="" selected="selected">Select countries</option>
<optgroup label="Popular Among Customers">
    <option value="CN">China</option>
    <option value="AU">Australia</option>
    <option value="CA">Canada</option>
    <option value="DE">Germany</option>
    <option value="FR">France</option>
    <option value="US">U.S.A</option>
    <option value="JP">Japan</option>
    <option value="TW">Taiwan</option>
    <option value="HK">Hong Kong</option>
    <option value="SG">Singapore</option>
    <option value="NZ">New Zealand</option>
    <option value="GB">Britain</option>
</optgroup>
<optgroup label="Country list">
    <option value="AL">Albania</option>
    <option value="DZ">Algeria</option>
    <option value="AF">Afghanistan</option>
    <option value="AR">Argentina</option>
    <option value="AE">The United Arab Emirates</option>
    <option value="AW">Aruba</option>
    <option value="AZ">Azerbaijan</option>
    <option value="AD">Andorra</option>
    <option value="AO">Angola</option>
    <option value="AI">Anguilla</option>
    <option value="AG">Antigua and Barbuda</option>
    <option value="AT">Austria</option>
    <option value="AS">American Samoa</option>
    <option value="AM">Armenia</option>
    <option value="BS">Bahamas</option>
    <option value="BH">Bahrain</option>
    <option value="BB">Barbados</option>
    <option value="BR">Brazil</option>
    <option value="BY">Belarus</option>
    <option value="BM">Bermuda</option>
    <option value="BG">Bulgaria</option>
    <option value="BJ">Benin</option>
    <option value="BE">Belgium</option>
    <option value="BW">botswana</option>
    <option value="BO">bolivia</option>
    <option value="BZ">Belize</option>
    <option value="BT">Bhutan</option>
    <option value="BA">Bosnia and Herzegovina</option>
    <option value="BF">burkina faso</option>
    <option value="BI">burundi</option>
    <option value="BV">Bouvet Island</option>
    <option value="BD">Bengal</option>
    <option value="BN">Brunei0</option>
    <option value="VG">british virgin islands</option>
    <option value="IO">British India Ocean Territory</option>
    <option value="CL">Chile</option>
    <option value="CF">Central African Republic</option>
    <option value="KH">Cambodia</option>
    <option value="CY">Cyprus</option>
    <option value="CZ">Czech</option>
    <option value="CM">Cameroon</option>
    <option value="KY">Cayman Islands</option>
    <option value="CC">Cocos (Keeling Islands)</option>
    <option value="HR">Croatia</option>
    <option value="KM">Comoros</option>
    <option value="CI">Cote d'Ivoire</option>
    <option value="CK">Cook Islands</option>
    <option value="CW">Curacao</option>
    <option value="CV">Cape Verde</option>
    <option value="CD">Congo (DRC)</option>
    <option value="CG">Congo (cloth)</option>
    <option value="CO">Columbia</option>
    <option value="CR">Costa Rica</option>
    <option value="CU">Cuba</option>
    <option value="TD">Chad</option>
    <option value="CX">Christmas Island</option>
    <option value="DM">Dominica</option>
    <option value="DO">Dominican</option>
    <option value="DK">Denmark</option>
    <option value="DJ">Djibouti</option>
    <option value="BQ">Dutch Caribbean</option>
    <option value="EG">Egypt</option>
    <option value="ET">Ethiopia</option>
    <option value="EE">Estonia</option>
    <option value="EC">Ecuador</option>
    <option value="ER">Eritrea</option>
    <option value="GQ">Equatorial Guinea</option>
    <option value="FI">Finland</option>
    <option value="FO">Faroe Islands</option>
    <option value="PF">French Polynesia</option>
    <option value="GF">French Guiana</option>
    <option value="TF">French Southern Territories</option>
    <option value="FK">Falkland Islands</option>
    <option value="FJ">Fiji</option>
    <option value="GM">Gambia</option>
    <option value="GL">Greenland</option>
    <option value="GD">Grenada</option>
    <option value="GE">Georgia</option>
    <option value="GG">Guernsey</option>
    <option value="GU">Guam</option>
    <option value="GY">Guyana</option>
    <option value="GN">Guinea</option>
    <option value="GW">Guinea-Bissau</option>
    <option value="GH">Ghana</option>
    <option value="GA">Gabon</option>
    <option value="GI">Gibraltar</option>
    <option value="GP">guadeloupe</option>
    <option value="GR">Greece</option>
    <option value="GT">Guatemala</option>
    <option value="HM">Hird island and Macdonald Islands</option>
    <option value="HT">Haiti</option>
    <option value="HN">Honduras</option>
    <option value="HU">Hungary</option>
    <option value="IE">Ireland</option>
    <option value="IS">Iceland</option>
    <option value="IT">Italy</option>
    <option value="IR">Iran</option>
    <option value="IQ">Iraq</option>
    <option value="IL">Israel</option>
    <option value="IN">India</option>
    <option value="ID">Indonesia</option>
    <option value="JM">Jamaica</option>
    <option value="JO">Jordan</option>
    <option value="JE">Jersey</option>
    <option value="KW">Kuwait</option>
    <option value="KE">Kenya</option>
    <option value="KZ">Kazakhstan</option>
    <option value="KG">Kyrgyzstan standard</option>
    <option value="KI">Kiribati</option>
    <option value="LV">Latvia</option>
    <option value="LS">Lesotho</option>
    <option value="LA">Laos</option>
    <option value="LB">Lebanon</option>
    <option value="LR">Liberia</option>
    <option value="LY">Libya</option>
    <option value="LT">Lithuania</option>
    <option value="LI">Liechtenstein</option>
    <option value="LU">Luxembourg</option>
    <option value="MO">Macao</option>
    <option value="MV">Maldives</option>
    <option value="MT">Malta</option>
    <option value="MW">Malawi</option>
    <option value="MY">Malaysia</option>
    <option value="ML">Mali</option>
    <option value="MK">Macedonia</option>
    <option value="MH">Marshall Islands</option>
    <option value="YT">Mayotte</option>
    <option value="MR">Mauritania</option>
    <option value="MU">Mauritius</option>
    <option value="ME">Montenegro</option>
    <option value="MN">Mongolia</option>
    <option value="MS">Montserrat</option>
    <option value="FM">Micronesia</option>
    <option value="MM">Myanmar</option>
    <option value="MD">Moldova</option>
    <option value="MA">Morocco</option>
    <option value="MC">Monaco</option>
    <option value="MZ">Mozambique</option>
    <option value="MX">Mexico</option>
    <option value="MQ">Martinique</option>
    <option value="MG">Madagascar</option>
    <option value="NP">Nepal</option>
    <option value="NL">Netherlands</option>
    <option value="NI">Nicaragua</option>
    <option value="NE">Niger</option>
    <option value="NG">Nigeria</option>
    <option value="NU">Niue</option>
    <option value="MP">Northern Mariana Islands</option>
    <option value="KP">North Korea</option>
    <option value="NA">Namibia</option>
    <option value="NR">Nauru</option>
    <option value="NC">New Caledonia</option>
    <option value="NF">Norfolk Island</option>
    <option value="NO">Norway</option>
    <option value="OM">Oman</option>
    <option value="AX">Oran Islands</option>
    <option value="PG">papua new guinea</option>
    <option value="PK">Pakistan</option>
    <option value="PY">Paraguay</option>
    <option value="PS">Palestine</option>
    <option value="PA">Panama</option>
    <option value="PE">Peru</option>
    <option value="PR">Puerto Rico</option>
    <option value="PL">poland</option>
    <option value="PW">Palau</option>
    <option value="PN">Pitt Kaine Islands</option>
    <option value="PT">Portugal</option>
    <option value="QA">Qatar</option>
    <option value="RU">Russia</option>
    <option value="RE">Reunion Island</option>
    <option value="RW">Rwanda</option>
    <option value="RO">Romania</option>
    <option value="SE">Sweden</option>
    <option value="SX">Sint Maarten</option>
    <option value="CH">Switzerland</option>
    <option value="SV">Salvatore</option>
    <option value="WS">Samoa</option>
    <option value="RS">Serbia</option>
    <option value="SL">sierra leone</option>
    <option value="SN">Senegal</option>
    <option value="SC">Seychelles</option>
    <option value="SA">Saudi Arabia</option>
    <option value="BL">Saint-Barthelemy</option>
    <option value="PM">San Pierre and the secret clone</option>
    <option value="MF">saint martin</option>
    <option value="ST">Sao Tome and Principe</option>
    <option value="SH">St. Helena</option>
    <option value="KN">Saint Kitts and Nevis</option>
    <option value="LC">Saint Lucia</option>
    <option value="SM">San Marino</option>
    <option value="VC">Saint Vincent and the Grenadines</option>
    <option value="LK">Sri Lanka</option>
    <option value="SK">Slovakia</option>
    <option value="SI">Slovenia</option>
    <option value="SJ">Svalbard and Jan Mayen</option>
    <option value="SZ">Swaziland</option>
    <option value="SD">Sultan</option>
    <option value="SR">Suriname</option>
    <option value="SB">Solomon Islands</option>
    <option value="ZA">South Africa</option>
    <option value="GS">South Georgia and the South Sandwich Islands</option>
    <option value="SS">South Sudan</option>
    <option value="ES">Spain</option>
    <option value="SY">Syria</option>
    <option value="TJ">Tajikistan</option>
    <option value="TH">Thailand</option>
    <option value="TO">Tonga</option>
    <option value="TZ">Tanzania</option>
    <option value="TC">Turks and Caicos Islands</option>
    <option value="TT">Trinidad and Tobago</option>
    <option value="TR">Turkey</option>
    <option value="TM">Turkmenistan</option>
    <option value="TN">Tunisia</option>
    <option value="TV">Tuvalu</option>
    <option value="TK">Tokelau Islands</option>
    <option value="TL">Timor-Leste</option>
    <option value="TG">Togo</option>
    <option value="PH">The Philippines</option>
    <option value="KR">The Republic of Korea</option>
    <option value="IM">The Isle of man.</option>
    <option value="AN">The Netherlands Antilles</option>
    <option value="UG">Uganda</option>
    <option value="UA">Ukraine</option>
    <option value="UY">Uruguay</option>
    <option value="UZ">Uzbekistan</option>
    <option value="VE">Venezuela</option>
    <option value="VA">Vatican</option>
    <option value="VI">Virgin Islands</option>
    <option value="VU">Vanuatu</option>
    <option value="VN">Vietnam</option>
    <option value="WF">Wallis and Futuna Islands</option>
    <option value="EH">West Sahara</option>
    <option value="YE">Yemen</option>
    <option value="ZM">Zambia</option>
    <option value="ZW">zimbabwe</option>
</optgroup>