<option value="" selected="selected">选择国家</option>
<optgroup label="热门目的地国家/地区">
    <option value="CN">中国(China)</option>
    <option value="AU">澳大利亚(Australia)</option>
    <option value="CA">加拿大(Canada)</option>
    <option value="DE">德国(Germany)</option>
    <option value="FR">法国(France)</option>
    <option value="US">美国(U.S.A)</option>
    <option value="JP">日本(Japan)</option>
    <option value="TW">台湾(Taiwan)</option>
    <option value="HK">香港(Hong Kong)</option>
    <option value="SG">新加坡(Singapore)</option>
    <option value="NZ">新西兰(New Zealand)</option>
    <option value="GB">英国(Britain)</option>
</optgroup>
<optgroup label="国家列表">
    <option value="AL">阿尔巴尼亚(Albania)</option>
    <option value="DZ">阿尔及利亚(Algeria)</option>
    <option value="AF">阿富汗(Afghanistan)</option>
    <option value="AR">阿根廷(Argentina)</option>
    <option value="AE">阿联酋(The United Arab Emirates)</option>
    <option value="AW">阿鲁巴(Aruba)</option>
    <option value="OM">阿曼(Oman)</option>
    <option value="AZ">阿塞拜疆(Azerbaijan)</option>
    <option value="IE">爱尔兰(Ireland)</option>
    <option value="EG">埃及(Egypt)</option>
    <option value="ET">埃塞俄比亚(Ethiopia)</option>
    <option value="EE">爱沙尼亚(Estonia)</option>
    <option value="AD">安道尔(Andorra)</option>
    <option value="AO">安哥拉(Angola)</option>
    <option value="AI">安奎拉(Anguilla)</option>
    <option value="AG">安提瓜和巴布达(Antigua and Barbuda)</option>
    <option value="AT">奥地利(Austria)</option>
    <option value="AX">奥兰群岛(Oran Islands)</option>
    <option value="MO">澳门(Macao)</option>
    <option value="BB">巴巴多斯(Barbados)</option>
    <option value="PG">巴布亚新几内亚(papua new guinea)</option>
    <option value="BS">巴哈马(Bahamas)</option>
    <option value="PK">巴基斯坦(Pakistan)</option>
    <option value="BH">巴林(Bahrain)</option>
    <option value="PY">巴拉圭(Paraguay)</option>
    <option value="PS">巴勒斯坦(Palestine)</option>
    <option value="PA">巴拿马(Panama)</option>
    <option value="BR">巴西(Brazil)</option>
    <option value="BY">白俄罗斯(Belarus)</option>
    <option value="BM">百慕大(Bermuda)</option>
    <option value="BG">保加利亚(Bulgaria)</option>
    <option value="MP">北马里亚那群岛(Northern Mariana Islands)</option>
    <option value="BJ">贝宁(Benin)</option>
    <option value="BE">比利时(Belgium)</option>
    <option value="PE">秘鲁(Peru)</option>
    <option value="IS">冰岛(Iceland)</option>
    <option value="BW">博茨瓦纳(botswana)</option>
    <option value="PR">波多黎各(Puerto Rico)</option>
    <option value="BA">波黑(Bosnia and Herzegovina)</option>
    <option value="PL">波兰(poland)</option>
    <option value="BO">玻利维亚(bolivia)</option>
    <option value="BZ">伯利兹(Belize)</option>
    <option value="BT">不丹(Bhutan)</option>
    <option value="BF">布基纳法索(burkina faso)</option>
    <option value="BI">布隆迪(burundi)</option>
    <option value="BV">布韦岛(Bouvet Island)</option>
    <option value="KP">朝鲜(North Korea)</option>
    <option value="GQ">赤道几内亚(Equatorial Guinea)</option>
    <option value="DK">丹麦(Denmark)</option>
    <option value="TL">东帝汶(Timor-Leste)</option>
    <option value="TG">多哥(Togo)</option>
    <option value="DM">多米尼克(Dominica)</option>
    <option value="DO">多米尼加(Dominican)</option>
    <option value="EC">厄瓜多尔(Ecuador)</option>
    <option value="ER">厄立特里亚(Eritrea)</option>
    <option value="RU">俄罗斯(Russia)</option>
    <option value="FO">法罗群岛(Faroe Islands)</option>
    <option value="PF">法属波利尼西亚(French Polynesia)</option>
    <option value="GP">法属瓜德罗普岛(guadeloupe)</option>
    <option value="GF">法属圭亚那(French Guiana)</option>
    <option value="MQ">法属马提尼克岛(Martinique)</option>
    <option value="TF">法属南部领地(French Southern Territories)</option>
    <option value="MF">法属圣马丁(saint martin)</option>
    <option value="VA">梵蒂冈(Vatican)</option>
    <option value="FJ">斐济(Fiji)</option>
    <option value="PH">菲律宾(The Philippines)</option>
    <option value="FI">芬兰(Finland)</option>
    <option value="CV">佛得角(Cape Verde)</option>
    <option value="FK">福克兰群岛(Falkland Islands)</option>
    <option value="GM">冈比亚(Gambia)</option>
    <option value="CG">刚果（布）(Congo (cloth))</option>
    <option value="CD">刚果（金）(Congo (DRC))</option>
    <option value="GL">格陵兰岛(Greenland)</option>
    <option value="GD">格林纳达(Grenada)</option>
    <option value="GE">格鲁吉亚(Georgia)</option>
    <option value="CO">哥伦比亚(Columbia)</option>
    <option value="CR">哥斯达黎加(Costa Rica)</option>
    <option value="GG">根西岛(Guernsey)</option>
    <option value="CU">古巴(Cuba)</option>
    <option value="GU">关岛(Guam)</option>
    <option value="GY">圭亚那(Guyana)</option>
    <option value="KZ">哈萨克斯坦(Kazakhstan)</option>
    <option value="HM">赫德岛和麦克唐纳群岛(Hird island and Macdonald Islands)</option>
    <option value="HT">海地(Haiti)</option>
    <option value="KR">韩国(The Republic of Korea)</option>
    <option value="NL">荷兰(Netherlands)</option>
    <option value="BQ">荷兰加勒比(Dutch Caribbean)</option>
    <option value="AN">荷属安的列斯群岛(The Netherlands Antilles)</option>
    <option value="SX">荷属圣马丁(Sint Maarten)</option>
    <option value="ME">黑山(Montenegro)</option>
    <option value="HN">洪都拉斯(Honduras)</option>
    <option value="DJ">吉布提(Djibouti)</option>
    <option value="KG">吉尔吉斯斯但(Kyrgyzstan standard)</option>
    <option value="KI">基里巴斯(Kiribati)</option>
    <option value="GN">几内亚(Guinea)</option>
    <option value="GW">几内亚比绍(Guinea-Bissau)</option>
    <option value="GH">加纳(Ghana)</option>
    <option value="GA">加蓬(Gabon)</option>
    <option value="KH">柬埔寨(Cambodia)</option>
    <option value="CZ">捷克(Czech)</option>
    <option value="ZW">津巴布韦(zimbabwe)</option>
    <option value="CM">喀麦隆(Cameroon)</option>
    <option value="QA">卡塔尔(Qatar)</option>
    <option value="KY">开曼群岛(Cayman Islands)</option>
    <option value="CC">科科斯（基林）群岛(Cocos (Keeling Islands))</option>
    <option value="HR">克罗地亚(Croatia)</option>
    <option value="KM">科摩罗(Comoros)</option>
    <option value="CI">科特迪瓦(Cote d'Ivoire)</option>
    <option value="KW">科威特(Kuwait)</option>
    <option value="KE">肯尼亚(Kenya)</option>
    <option value="CK">库克群岛(Cook Islands)</option>
    <option value="CW">库拉索岛(Curacao)</option>
    <option value="LV">拉脱维亚(Latvia)</option>
    <option value="LS">莱索托(Lesotho)</option>
    <option value="LA">老挝(Laos)</option>
    <option value="LB">黎巴嫩(Lebanon)</option>
    <option value="LR">利比里亚(Liberia)</option>
    <option value="LY">利比亚(Libya)</option>
    <option value="LT">立陶宛(Lithuania)</option>
    <option value="LI">列支敦士登(Liechtenstein)</option>
    <option value="RE">留尼汪岛(Reunion Island)</option>
    <option value="LU">卢森堡(Luxembourg)</option>
    <option value="RW">卢旺达(Rwanda)</option>
    <option value="RO">罗马尼亚(Romania)</option>
    <option value="MG">马达加斯加(Madagascar)</option>
    <option value="IM">马恩岛(The Isle of man.)</option>
    <option value="MV">马尔代夫(Maldives)</option>
    <option value="MT">马耳他(Malta)</option>
    <option value="MW">马拉维(Malawi)</option>
    <option value="MY">马来西亚(Malaysia)</option>
    <option value="ML">马里(Mali)</option>
    <option value="MK">马其顿(Macedonia)</option>
    <option value="MH">马绍尔群岛(Marshall Islands)</option>
    <option value="YT">马约特岛(Mayotte)</option>
    <option value="MR">毛里塔尼亚(Mauritania)</option>
    <option value="MU">毛里求斯(Mauritius)</option>
    <option value="AS">美属萨摩亚(American Samoa)</option>
    <option value="VI">美属维尔京群岛(Virgin Islands)</option>
    <option value="MN">蒙古国(Mongolia)</option>
    <option value="BD">孟加拉(Bengal)</option>
    <option value="MS">蒙特塞拉特岛(Montserrat)</option>
    <option value="FM">密克罗尼西亚联邦(Micronesia)</option>
    <option value="MM">缅甸(Myanmar)</option>
    <option value="MD">摩尔多瓦(Moldova)</option>
    <option value="MA">摩洛哥(Morocco)</option>
    <option value="MC">摩纳哥(Monaco)</option>
    <option value="MZ">莫桑比克(Mozambique)</option>
    <option value="MX">墨西哥(Mexico)</option>
    <option value="NA">纳米比亚(Namibia)</option>
    <option value="NR">瑙鲁(Nauru)</option>
    <option value="ZA">南非(South Africa)</option>
    <option value="GS">南乔治亚岛和南桑威奇群岛(South Georgia and the South Sandwich Islands)</option>
    <option value="SS">南苏丹(South Sudan)</option>
    <option value="NP">尼泊尔(Nepal)</option>
    <option value="NI">尼加拉瓜(Nicaragua)</option>
    <option value="NE">尼日尔(Niger)</option>
    <option value="NG">尼日利亚(Nigeria)</option>
    <option value="NU">纽埃(Niue)</option>
    <option value="NF">诺福克岛(Norfolk Island)</option>
    <option value="NO">挪威(Norway)</option>
    <option value="PW">帕劳(Palau)</option>
    <option value="PN">皮特凯恩群岛(Pitt Kaine Islands)</option>
    <option value="PT">葡萄牙(Portugal)</option>
    <option value="SE">瑞典(Sweden)</option>
    <option value="CH">瑞士(Switzerland)</option>
    <option value="SV">萨尔瓦多(Salvatore)</option>
    <option value="WS">萨摩亚(Samoa)</option>
    <option value="RS">塞尔维亚(Serbia)</option>
    <option value="SL">塞拉利昂(sierra leone)</option>
    <option value="SN">塞内加尔(Senegal)</option>
    <option value="CY">塞浦路斯(Cyprus)</option>
    <option value="SC">塞舌尔(Seychelles)</option>
    <option value="SA">沙特阿拉伯(Saudi Arabia)</option>
    <option value="BL">圣巴泰勒米岛(Saint-Barthelemy)</option>
    <option value="PM">圣彼埃尔和密克隆(San Pierre and the secret clone)</option>
    <option value="CX">圣诞岛(Christmas Island)</option>
    <option value="ST">圣多美和普林西比(Sao Tome and Principe)</option>
    <option value="SH">圣赫勒拿岛(St. Helena)</option>
    <option value="KN">圣克里斯托弗和尼维斯岛(Saint Kitts and Nevis)</option>
    <option value="LC">圣卢西亚(Saint Lucia)</option>
    <option value="SM">圣马力诺(San Marino)</option>
    <option value="VC">圣文森特和格林纳丁斯(Saint Vincent and the Grenadines)</option>
    <option value="LK">斯里兰卡(Sri Lanka)</option>
    <option value="SK">斯洛伐克(Slovakia)</option>
    <option value="SI">斯洛文尼亚(Slovenia)</option>
    <option value="SJ">斯瓦尔巴群岛和扬马延岛(Svalbard and Jan Mayen)</option>
    <option value="SZ">斯威士兰(Swaziland)</option>
    <option value="SD">苏丹(Sultan)</option>
    <option value="SR">苏里南(Suriname)</option>
    <option value="SB">所罗门群岛(Solomon Islands)</option>
    <option value="TJ">塔吉克斯坦(Tajikistan)</option>
    <option value="TH">泰国(Thailand)</option>
    <option value="TO">汤加(Tonga)</option>
    <option value="TZ">坦桑尼亚(Tanzania)</option>
    <option value="TC">特克斯和凯科斯群岛(Turks and Caicos Islands)</option>
    <option value="TT">特立尼达和多巴哥(Trinidad and Tobago)</option>
    <option value="TR">土耳其(Turkey)</option>
    <option value="TM">土库曼斯坦(Turkmenistan)</option>
    <option value="TN">突尼斯(Tunisia)</option>
    <option value="TV">图瓦卢(Tuvalu)</option>
    <option value="TK">托克劳群岛(Tokelau Islands)</option>
    <option value="WF">瓦利斯和富图纳群岛(Wallis and Futuna Islands)</option>
    <option value="VU">瓦努阿图(Vanuatu)</option>
    <option value="GT">危地马拉(Guatemala)</option>
    <option value="VE">委内瑞拉(Venezuela)</option>
    <option value="BN">文莱(Brunei0)</option>
    <option value="UG">乌干达(Uganda)</option>
    <option value="UA">乌克兰(Ukraine)</option>
    <option value="UY">乌拉圭(Uruguay)</option>
    <option value="UZ">乌兹别克斯坦(Uzbekistan)</option>
    <option value="ES">西班牙(Spain)</option>
    <option value="GR">希腊(Greece)</option>
    <option value="EH">西撒哈拉(West Sahara)</option>
    <option value="NC">新喀里多尼亚(New Caledonia)</option>
    <option value="HU">匈牙利(Hungary)</option>
    <option value="SY">叙利亚(Syria)</option>
    <option value="JM">牙买加(Jamaica)</option>
    <option value="AM">亚美尼亚(Armenia)</option>
    <option value="YE">也门(Yemen)</option>
    <option value="IT">意大利(Italy)</option>
    <option value="IR">伊朗(Iran)</option>
    <option value="IQ">伊拉克(Iraq)</option>
    <option value="IL">以色列(Israel)</option>
    <option value="IN">印度(India)</option>
    <option value="ID">印度尼西亚(Indonesia)</option>
    <option value="VG">英属维京群岛(british virgin islands)</option>
    <option value="IO">英属印度洋领地(British India Ocean Territory)</option>
    <option value="JO">约旦(Jordan)</option>
    <option value="VN">越南(Vietnam)</option>
    <option value="ZM">赞比亚(Zambia)</option>
    <option value="JE">泽西岛(Jersey)</option>
    <option value="TD">乍得(Chad)</option>
    <option value="GI">直布罗陀(Gibraltar)</option>
    <option value="CL">智利(Chile)</option>
    <option value="CF">中非共和国(Central African Republic)</option>
</optgroup>